framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_DSN)%'
        pools:
            cache.popular_articles:
                adapter: cache.adapter.redis
                default_lifetime: 3600
                tags: true
            cache.heavy_queries:
                adapter: cache.adapter.redis
                default_lifetime: 1800
                tags: true
